name: GitHub Create State
on:
    workflow_dispatch: 
env:
    ARM_CLIENT_ID: "${{secrets.AZURE_CLIENT_ID}}"
    ARM_SUBSCRIPTION_ID: "${{secrets.AZURE_SUBSCRIPTION_ID}}"
    ARM_TENANT_ID: "${{secrets.AZURE_TENANT_ID}}"
    ARM_SECRET_CLIENT: "${{secrets.AZURE_SECRET_CLIENT}}"
jobs:
    terraform-plan:
        name: "Terraform plan"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: Terraform Init
              run: terraform init 
            - id: plan
              name: Terraform Plan
              run: terraform plan -no-color
            - id: apply
              name: Terraform Apply
              run: terraform apply -auto-approve 
            - id: get-access-key
              name: Get Access Key
              run: |
                PRIMARY_ACCESS_KEY=$(az storage account keys list --resource-group my-terraform-state-rg --account-name mytfstatesahca --query "[0].value" --output tsv)
                echo "::set-output name=primary_access_key::$PRIMARY_ACCESS_KEY"
                echo "$PRIMARY_ACCESS_KEY" > azure-storage-access-key.txt